routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['namespace' => 'App\Http\Controllers'], function()
{   
    Route::get('/', 'LoginController@index')->name('home');

    Route::get('/login', 'LoginController@index')->name('login');
    Route::post('/login', 'LoginController@loginAction')->name('login.action');
    
    Route::group(['middleware' => ['auth']], function() {
        Route::get('/logout', 'LogoutController@index')->name('logout');
    });

});

Route::namespace('App\Http\Controllers\Admin')->prefix('admin')->middleware('auth')->group(function () {
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');

        Route::get('/update_profile', 'UpdateProfileController@index')->name('admin.update_profile');
        Route::post('/update_profile_action', 'UpdateProfileController@action')->name('admin.update_profile_action');

    // ACL
    Route::name('acl.')->prefix('acl')->group(function () {

        Route::get('users', 'Acl\UsersController@index')->name('users.index');
        Route::get('users/userJson', 'Acl\UsersController@userJson')->name('users.userJson');
        Route::post('users/addform', 'Acl\UsersController@addform')->name('users.addform');
        Route::post('users/userPost', 'Acl\UsersController@userPost')->name('users.userPost');
        Route::post('users/editform', 'Acl\UsersController@editform')->name('users.editform');
        Route::delete('users/delete', 'Acl\UsersController@delete')->name('users.delete');

        Route::get('role', 'Acl\RoleController@index')->name('role.index');
        Route::get('role/roleJson', 'Acl\RoleController@roleJson')->name('role.roleJson');
    
    });

    // Kendaraan Masuk
    Route::name('kendaraan_masuk.')->prefix('kendaraan_masuk')->group(function () {

        Route::get('/', 'KendaraanMasuk\KendaraanMasukController@index')->name('index');

        Route::post('/kendaraan_masuk_post', 'KendaraanMasuk\KendaraanMasukController@kendaraanMasukPost')->name('kendaraanMasukPost');

        Route::post('/info_kendaraan_code', 'KendaraanMasuk\KendaraanMasukController@infoKendaraanByCode')->name('infoKendaraanCode');
        
        Route::get('/kendaraanTersediaJson', 'KendaraanMasuk\KendaraanMasukController@kendaraanTersediaJson')->name('kendaraanTersediaJson');
    });

    // Kendaraan Keluar
    Route::name('kendaraan_keluar.')->prefix('kendaraan_keluar')->group(function () {
        Route::get('/', 'KendaraanKeluar\KendaraanKeluarController@index')->name('index');

        Route::post('/kendaraan_keluar_post', 'KendaraanKeluar\kendaraanKeluarController@kendaraanKeluarPost')->name('kendaraanKeluarPost');

        Route::post('/info_kendaraan_code', 'KendaraanKeluar\KendaraanKeluarController@infoKendaraanByCode')->name('infoKendaraanCode');
    });

    // Pelaporan
    Route::name('pelaporan.')->prefix('pelaporan')->group(function () {
        Route::get('/', 'Pelaporan\PelaporanController@index')->name('index');

        Route::get('/pelaporan_json', 'Pelaporan\PelaporanController@pelaporanJson')->name('pelaporanJson');

        Route::get('/export', 'Pelaporan\PelaporanController@exportExcel')->name('exportExcel');

        
    });

    


});

app/Http/Controllers/admin/KendaraanMasuk/KendaraanMasukController.php
<?php

namespace App\Http\Controllers\admin\KendaraanMasuk;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\Vehicle;
use DataTables;
use Carbon\Carbon;

class KendaraanMasukController extends Controller
{
    private $mod_path = 'admin/kendaraan_masuk';

    function index(){
        if( access($this->mod_path, 'read') === false){
            die("Access denied");
        }

        return view('admin.pages.kendaraan_masuk.index');
    }

    function kendaraanMasukPost(Request $request){
        if( access($this->mod_path, 'create') === false){
            die("Access denied");
        }

        $rules['plat_number'] = 'required';


        $messages =[
              'plat_number.required'=>'Anda belum memasukkan tanda nomor kendaraan bermotor'
          ];

        $validator = Validator::make($request->all(), $rules, $messages);

        if ($validator->fails()){
            return response()->json(array(
                'success' => false,
                'errors' => $validator->getMessageBag()->toArray()

            ));
        }else{

            if( $this->isVehicleAvailable($request->plat_number) ){
                return response()->json(array(
                    'success'   => false,
                    'errors'    => array( ['Kendaraan masih berada dalam area parkir!'] )
                    )
                );
            }else{
                $vehicle = new Vehicle;
                $vehicle->plat_number  = preg_replace('/\s+/', '', $request->plat_number);
                $vehicle->code         = generateNumber(8);
                $vehicle->checkin_at   = now();
                $vehicle->created_at   = now();
                $vehicle->updated_at   = now();

                if( $vehicle->save() ){
                    return response()->json(array(
                        'success' => true,
                        'data'    => $vehicle->code
                    ), 200);
                }
            }
            
        }
    }

    function isVehicleAvailable($plat_number){
        if( access($this->mod_path, 'create') === false){
            die("Access denied");
        }

        $count = Vehicle::where('plat_number', $plat_number)->whereNull('checkout_at')->count();

        if( $count > 0 ){
            return true;
        }else{
            return false;
        }  
    }

    function infoKendaraanByCode(Request $request){
        $code = $request->code;

        $q = Vehicle::where('code', $code);
        if( $q->count() == 1 ){
            $data = $q->first();
        }else{
            $data = null;
        }

        return view('admin.pages.kendaraan_masuk.info', ['data' => $data])->render();
    }

    function kendaraanTersediaJson(Request $request){

        if( access($this->mod_path, 'create') === false){
            die("Access denied");
        }

        if ($request->ajax()) {
            $data = Vehicle::whereNull('checkout_at')->latest()->get();

            return Datatables::of($data)
                ->addIndexColumn()

                ->editColumn('checkin_at', function ($request) {
                    // return Carbon::createFromFormat('Y-m-d H:i:s', $request->checkin_at)->toDateTimeString();
                    return date("d-m-Y H:i:s", strtotime($request->checkin_at));
                })
                ->rawColumns(['nopol'])
                ->make(true);
        }
    }
}

resources/views/admin/pages/kendaraan_masuk/index.blade.php
@extends('admin.layout.main')


@section('title', 'Kendaraan Masuk')

@section('breadcrumb')
<!-- BEGIN BREADCRUMB -->
<div class="col-12 mb-3">
	<nav class="widget breadcrumb-two" aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item active">
				<a href="">Kendaraan Masuk</a>
			</li>
			<li class="breadcrumb-item"><a href="javascript:void(0);">&nbsp;</a></li>
		</ol>
	</nav>
</div>
<!-- ./END BREADCRUMB -->
@endsection

@section('content')
	<div class="row">
		<div class="col-md-6">
			<p>Masukkan Tanda Nomor Kendaraan Bermotor</p>
			<form method="POST" action="{{ route('kendaraan_masuk.kendaraanMasukPost') }}" id="vehicleInputForm" onsubmit="vehicleInput(event)">
              	@csrf
              	<!-- Input Box -->
			    <div class="input-group form-container">
			      <input type="text" name="plat_number" class="form-control search-input" placeholder="Ex. B1234TQ" autofocus="autofocus" autocomplete="off">
			          
		          <span class="input-group-btn">
		            <button class="btn btn-search">
		              <img src="{{ url('assets/images/icons/search.png') }}" width="40">
		            </button>
		          </span>

			    </div>
      			<!-- ./End of input box -->
            </form>
            

            <div class="alert custom-alert-1 mb-4 mt-3" role="alert" id="errorMessageBox" style="display: none;">
                <div class="media">
                    <div class="alert-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-alert-triangle"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12" y2="17"></line></svg>
                    </div>

                    <div class="media-body">
                        <div class="alert-text" id="errorMessage"></div>
                    </div>

                </div>
            </div>

		</div>

		<div class="col-md-6" id="vehicleInfo">
			
		</div>

		<div class="col-md-12 mt-5">
			<h3 class="primary-color">Kendaraan di area parkir</h3>
			<div class="table-responsive">
	            <table class="table table-hover" id="datatable-grid">
	                <thead>
	                    <tr>
	                    	<th>Nomor Polisi</th>
	                        <th>Kode</th>
	                        <th>Waktu Masuk</th>
	                    </tr>
	                </thead>
	                
	            </table>
	        </div>
		</div>
	</div>
@endsection

@section('script')
<script src="https://cdn.jsdelivr.net/jsbarcode/3.3.20/JsBarcode.all.min.js"></script>

<script type="text/javascript">
	
	$(document).ready(function() {
        var dataTable = $('#datatable-grid').DataTable( {
			drawCallback: function () {
			    $('[data-toggle="tooltip"]').tooltip();
			},
			processing    : false,
			serverSide    : true,
			bLengthChange : true,
			"oLanguage": {
				"sProcessing": "loading...",
                "oPaginate": { 
                	"sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>', "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>' 
                },

            	"sInfo": "Menampilkan halaman _PAGE_ of _PAGES_, total rekod _TOTAL_",
            	"sInfoEmpty": "Menampilkan halaman _PAGE_ of _PAGES_, total rekod _TOTAL_",
            
            	"sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
            
            	"sSearchPlaceholder": "Cari...",

           		"sLengthMenu": "Filter :  _MENU_",

           		"sEmptyTable": "Tidak ada data untuk ditampilkan"
            },
            "stripeClasses": [],
            
			ajax :{
			    url :"{{ route('kendaraan_masuk.kendaraanTersediaJson') }}", // json datasource
			    type: "get",  // method  , by default get
			    error: function(request, status, error){  // error handling
			        
			        console.log(request.responseText);
			        
			    }
			},
			columns: [
				{data: 'plat_number'},
				{data: 'code'},
	            {data: 'checkin_at'},
	        ]

		});
    });

	function vehicleInput(event){
		event.preventDefault();

		var data = new FormData($("#vehicleInputForm")[0]);
	    var action  = $('#vehicleInputForm').attr('action');

	    $.ajax({
	        'type': 'POST',
	        'url': action,
	        dataType: 'json',
	        'data': data,
	        'processData': false,
	        'contentType': false,
	        'cache': false,

	        beforeSend: function(){
	            $("#loader").show();
	            $("#errorMessage").html("");
	        },
	        success: function(data) { 
	            if(data.success){
	            	$('#datatable-grid').DataTable().ajax.reload();
	                getVehicleInfo(data.data)
	            }else{
	               	
	                $.each(data.errors, function (key, val) {
	                    console.log(val)
	                
	                    $("#errorMessage").append(val[0]);

	                    $("#errorMessageBox").show();

	                    setTimeout(() => {
	                    	$("#errorMessageBox").hide();
	                    }, 4000);

	                });

	                $("html, body").animate({ 
	                    scrollTop: 0 
	                }, 600);
	                
	            }             
	            
	        },error: function(request, status, error){
	           console.log(request.responseText);
	        },complete: function(){
	            $("#loader").hide();
	        }
	    }); 
	}

	function getVehicleInfo(code){
	    $.ajax({
	        url: "{{ route('kendaraan_masuk.infoKendaraanCode') }}",
	        type: "post",
	        data: {code: code, "_token": $('meta[name="csrf_token"]').attr('content') },
	        cache: false,
	        beforeSend: function(){
	            $("#loader").show();
	        },
	        success: function(res) { 
	        	$("#vehicleInfo").html(res);

	        	$("#barcode").JsBarcode(code);

	        },error: function(request, status, error){
	           console.log(request.responseText);
	        },complete: function(){
	            $("#loader").hide();
	        }
	    });
		
	}
</script>
@endsection

resources/views/admin/pages/kendaraan_masuk/info.blade.php
<div class="panel-info-kendaraan pt-3 pb-3">
	<h4 class="primary-color text-center">Informasi Kendaraan Bermotor</h4>
	@if( !empty($data) )
		<h6 class="text-center">Tanda Nomor Kendaraan Bermotor</h6>
		<h3 class="text-center primary-color">{{ $data->plat_number }}</h3>
		<div class="mx-auto">
			<img id="barcode" class="mx-auto d-block"/>
		</div>
		<h6 class="text-center mt-3">Masuk: {{date("d-m-Y H:i:s", strtotime($data->checkin_at))}}</h6>
		
	@endif
</div>