routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['namespace' => 'App\Http\Controllers'], function()
{   
    Route::get('/', 'LoginController@index')->name('home');

    Route::get('/login', 'LoginController@index')->name('login');
    Route::post('/login', 'LoginController@loginAction')->name('login.action');
    
    Route::group(['middleware' => ['auth']], function() {
        Route::get('/logout', 'LogoutController@index')->name('logout');
    });

});

Route::namespace('App\Http\Controllers\Admin')->prefix('admin')->middleware('auth')->group(function () {
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');

        Route::get('/update_profile', 'UpdateProfileController@index')->name('admin.update_profile');
        Route::post('/update_profile_action', 'UpdateProfileController@action')->name('admin.update_profile_action');

    // ACL
    Route::name('acl.')->prefix('acl')->group(function () {

        Route::get('users', 'Acl\UsersController@index')->name('users.index');
        Route::get('users/userJson', 'Acl\UsersController@userJson')->name('users.userJson');
        Route::post('users/addform', 'Acl\UsersController@addform')->name('users.addform');
        Route::post('users/userPost', 'Acl\UsersController@userPost')->name('users.userPost');
        Route::post('users/editform', 'Acl\UsersController@editform')->name('users.editform');
        Route::delete('users/delete', 'Acl\UsersController@delete')->name('users.delete');

        Route::get('role', 'Acl\RoleController@index')->name('role.index');
        Route::get('role/roleJson', 'Acl\RoleController@roleJson')->name('role.roleJson');
    
    });

    // Kendaraan Masuk
    Route::name('kendaraan_masuk.')->prefix('kendaraan_masuk')->group(function () {

        Route::get('/', 'KendaraanMasuk\KendaraanMasukController@index')->name('index');

        Route::post('/kendaraan_masuk_post', 'KendaraanMasuk\KendaraanMasukController@kendaraanMasukPost')->name('kendaraanMasukPost');

        Route::post('/info_kendaraan_code', 'KendaraanMasuk\KendaraanMasukController@infoKendaraanByCode')->name('infoKendaraanCode');
        
        Route::get('/kendaraanTersediaJson', 'KendaraanMasuk\KendaraanMasukController@kendaraanTersediaJson')->name('kendaraanTersediaJson');
    });

    // Kendaraan Keluar
    Route::name('kendaraan_keluar.')->prefix('kendaraan_keluar')->group(function () {
        Route::get('/', 'KendaraanKeluar\KendaraanKeluarController@index')->name('index');

        Route::post('/kendaraan_keluar_post', 'KendaraanKeluar\kendaraanKeluarController@kendaraanKeluarPost')->name('kendaraanKeluarPost');

        Route::post('/info_kendaraan_code', 'KendaraanKeluar\KendaraanKeluarController@infoKendaraanByCode')->name('infoKendaraanCode');
    });

    // Pelaporan
    Route::name('pelaporan.')->prefix('pelaporan')->group(function () {
        Route::get('/', 'Pelaporan\PelaporanController@index')->name('index');

        Route::get('/pelaporan_json', 'Pelaporan\PelaporanController@pelaporanJson')->name('pelaporanJson');

        Route::get('/export', 'Pelaporan\PelaporanController@exportExcel')->name('exportExcel');

        
    });

    


});

app/Http/Controllers/admin/Acl/RoleController.php
<?php

namespace App\Http\Controllers\admin\Acl;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Roles;
use DataTables;

class RoleController extends Controller
{
    private $mod_path = 'admin/acl/role';

    function index(){
        if( access($this->mod_path, 'read') === false){
            die("Access denied");
        }

        return view('admin.pages.acl.role');
    }

    function roleJson(Request $request){
        if( access($this->mod_path, 'read') === false){
            die("Access denied");
        }
        
        if ($request->ajax()) {
            $data = Roles::latest()->get();
            return Datatables::of($data)
                ->addIndexColumn()
                ->editColumn('created_at', function ($request) {
                    return $request->created_at->format('Y-m-d H:i:s');
                })
                ->editColumn('updated_at', function ($request) {
                    return $request->updated_at->format('Y-m-d H:i:s');
                })
                ->addColumn('action', function($row){
                    $actionBtn = '';
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
    }
}

app/Http/Controllers/admin/Acl/UsersController.php
<?php

namespace App\Http\Controllers\admin\Acl;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\User;
use DataTables;

class UsersController extends Controller
{
    
    private $mod_path = 'admin/acl/users';

    function index(){
        if( access($this->mod_path, 'read') === false){
            die("Access denied");
        }

        return view('admin.pages.acl.users');
    }

    function userJson(Request $request){
        if( access($this->mod_path, 'read') === false){
            die("Access denied");
        }

        if ($request->ajax()) {
            $data = User::latest()->get();
            return Datatables::of($data)
                ->addIndexColumn()
                ->editColumn('created_at', function ($request) {
                    return $request->created_at->format('Y-m-d H:i:s');
                })
                ->editColumn('updated_at', function ($request) {
                    return $request->updated_at->format('Y-m-d H:i:s');
                })
                ->addColumn('action', function($row){
                    $actionBtn = '
                    <a href="javascript:void(0)" onClick="return load_form2(\''.route('acl.users.editform'). '\', \''.$row['id']. '\')"  data-toggle="modal" data-target="#ahsModalMD" class="edit btn btn-warning btn-sm">Edit</a> 

                    <a href="javascript:void(0)" onClick="return hapus(\''.route('acl.users.delete'). '\', \''.$row['id']. '\', `dt_reload`)" class="delete btn btn-danger btn-sm">Delete</a>';
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
    }

    function addform(){
        if( access($this->mod_path, 'create') === false){
            die("Access denied");
        }

        $title      = 'Tambah';
        $postRoute  = route('acl.users.userPost');
        return view('admin.pages.acl.add_user', ['title' => 'Tambah', 'postRoute' => $postRoute])->render();
    }

    function userPost(Request $request){
        if( access($this->mod_path, 'create') === false){
            die("Access denied");
        }

        $rules['username'] = 'required';
        $rules['email']     = 'required';
        $rules['full_name'] = 'required';
        $rules['role']      = 'required';
        $rules['password']  = 'required';

        if( $request->password )
        {
            $rules['password']  = 'required|min:8|same:password2';
            $rules['password2'] = 'required';
        }

        $messages =[
              'username.required'=>'Username harus diisi',
              'full_name.required' => 'Nama lengkap harus diisi',
              'email.required' => 'Email harus diiisi',
              'password.min' => 'Panjang password minimal 8 karakter',
              'password.same' => 'Verifikasi password harus sama dengan password',
              'password2.required' => 'Verifikasi password harus diisi',
              'role.required' => 'Role password harus diisi'
          ];



        $validator = Validator::make($request->all(), $rules, $messages);

        if ($validator->fails()){
            return response()->json(array(
                'success' => false,
                'errors' => $validator->getMessageBag()->toArray()

            ));
        }else{

            if( !empty($request->id) ){
                // update
                $user = User::find($request->id);
                $user->name         = $request->full_name;
                $user->username     = $request->username;
                $user->email        = $request->email;
                $user->password     = $request->password;
                $user->role_id      = $request->role;
                $user->updated_at   = now();
            }else{
                // create new record
                $user = new User;
                $user->name         = $request->full_name;
                $user->username     = $request->username;
                $user->email        = $request->email;
                $user->password     = $request->password;
                $user->role_id      = $request->role;
                $user->created_at   = now();
                $user->updated_at   = now();
            }

            if( $user->save() ){
                return response()->json(array('success' => true), 200);
            }
        }
    }

    function editform(Request $request){
        if( access($this->mod_path, 'update') === false){
            die("Access denied");
        }

        $id = $request->id;
        $title      = 'Update';
        $postRoute  = route('acl.users.userPost');

        $user = new User;
        $data = User::find($id);

        return view('admin.pages.acl.add_user', ['title' => $title, 'postRoute' => $postRoute, 'data' => $data] );
    }

    function delete(Request $request){
        if( access($this->mod_path, 'delete') === false){
            die("Access denied");
        }

        $rules['id'] = 'required';

        $messages =['id.required'=>'ID harus diisi'];

        $validator = Validator::make($request->all(), $rules, $messages);

        if ($validator->fails()){
            return response()->json(array(
                'success' => false,
                'errors' => $validator->getMessageBag()->toArray()

            ));
        }else{

            $user = User::find($request->id);

            if( $user->delete() ){
                return response()->json(array('success' => true), 200);
            }
        }
    }
}

resources/views/admin/pages/acl/add_user.blade.php
<h3 class="primary-color">{{ @$title }}</h3>

<div id="errorMessage"></div>

 <form role="form" enctype="multipart/form-data" accept-charset="utf-8" method="post" action="{{ @$postRoute }}" id="save" onsubmit="save(event, `dt_reload|dismissModalMD`);">
  @csrf
  
  <div class="form-row row">
      <input type="hidden" name="id" value="{{ @$data->id }}">
      <div class="form-group col-md-6">
          <label>Username<span class="text-danger">*</span></label><input type="text" name="username" value="{{ @$data->username }}" class="form-control" placeholder="Username" required />
      </div>
      <div class="form-group col-md-6">
          <label>Email<span class="text-danger">*</span></label><input type="text" name="email" value="{{ @$data->email }}" class="form-control" placeholder="Email" required />
      </div>

      <div class="form-group col-md-12">
          <label>Nama<span class="text-danger">*</span></label><input type="text" name="full_name" value="{{ @$data->name }}" class="form-control" placeholder="Nama"  />
      </div>

      <div class="form-group col-md-12">
          <label>Role<span class="text-danger">*</span></label><br />

          @foreach(getMasterRoles() as $role)

            <label class="custom-radio-button"><input type="radio" name="role" value="{{$role->id}}" {{ ($role->id==@$data->role_id)?"checked":"" }}/><span class="helping-el"></span><span class="label-text">{{$role->name}} </span></label>

          @endforeach

      </div>

      <div class="form-group col-md-6">
          <label>Password</label><input type="password" name="password" class="form-control" placeholder="Password" />
      </div>

      <div class="form-group col-md-6">
          <label>Verifikasi Password</label><input type="password" name="password2" class="form-control" placeholder="Password" />
      </div>
      
      <button type="submit" class="btn btn-primary">Simpan</button>
  </div>
</form>

</div>

resources/views/admin/pages/acl/role.blade.php
@extends('admin.layout.main')


@section('title', 'Role')

@section('breadcrumb')
<!-- BEGIN BREADCRUMB -->
<div class="col-12 mb-3">
	<nav class="widget breadcrumb-two" aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a href="">ACL</a>
			</li>
			<li class="breadcrumb-item active">
				<a href="">Role</a>
			</li>
			<li class="breadcrumb-item"><a href="javascript:void(0);">&nbsp;</a></li>
		</ol>
	</nav>
</div>
<!-- ./END BREADCRUMB -->
@endsection

@section('content')
<div class="panel-body mt-2">

        <div class="table-responsive">
            <table class="table table-hover" id="datatable-grid">
                <thead>
                    <tr>
                    	<th>Name</th>
                    	<th>Dibuat</th>
                    	<th>Update Terakhir</th>
                        <th>&nbsp; &nbsp; &nbsp;&nbsp; Aksi &nbsp;&nbsp; &nbsp;</th>
                    </tr>
                </thead>
                
            </table>
        </div>
</div>
@endsection


@section('script')
<script type="text/javascript">
	$(document).ready(function() {
		var dataTable = $('#datatable-grid').DataTable( {
			drawCallback: function () {
			    $('[data-toggle="tooltip"]').tooltip();
			},
			processing    : false,
			serverSide    : true,
			bLengthChange : true,
			"oLanguage": {
				"sProcessing": "loading...",
                "oPaginate": { 
                	"sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>', "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>' 
                },

            	"sInfo": "Menampilkan halaman _PAGE_ of _PAGES_, total rekod _TOTAL_",
            	"sInfoEmpty": "Menampilkan halaman _PAGE_ of _PAGES_, total rekod _TOTAL_",
            
            	"sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
            
            	"sSearchPlaceholder": "Cari...",

           		"sLengthMenu": "Filter :  _MENU_",

           		"sEmptyTable": "Tidak ada data untuk ditampilkan"
            },
            "stripeClasses": [],
            
			ajax :{
			    url :"{{ route('acl.role.roleJson') }}", // json datasource
			    type: "get",  // method  , by default get
			    error: function(request, status, error){  // error handling
			        
			        console.log(request.responseText);
			        
			    }
			},
			columns: [
				{data: 'name', name: 'name'},
				{data: 'created_at', name: 'created_at'},
				{data: 'updated_at', name: 'updated_at'},

	            {
	                data: 'action', 
	                name: 'action', 
	                orderable: true, 
	                searchable: true
	            },
	        ]

		});
        
    });

</script>
@endsection

resources/views/admin/pages/acl/users.blade.php
@extends('admin.layout.main')


@section('title', 'Users')

@section('breadcrumb')
<!-- BEGIN BREADCRUMB -->
<div class="col-12 mb-3">
	<nav class="widget breadcrumb-two" aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a href="">ACL</a>
			</li>
			<li class="breadcrumb-item active">
				<a href="">Users</a>
			</li>
			<li class="breadcrumb-item"><a href="javascript:void(0);">&nbsp;</a></li>
		</ol>
	</nav>
</div>
<!-- ./END BREADCRUMB -->
@endsection

@section('content')
<div class="panel-body mt-2">

		<!-- Button -->
		<div class="col-sm-12 mb-3">

            <a href="javascript:void(0)" onclick="loadAddForm()" data-toggle="modal" data-target="#ahsModalMD" class="btn btn-primary">Tambah 
            	<svg class="svg-inline--fa fa-plus-circle fa-w-16" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="plus-circle" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm144 276c0 6.6-5.4 12-12 12h-92v92c0 6.6-5.4 12-12 12h-56c-6.6 0-12-5.4-12-12v-92h-92c-6.6 0-12-5.4-12-12v-56c0-6.6 5.4-12 12-12h92v-92c0-6.6 5.4-12 12-12h56c6.6 0 12 5.4 12 12v92h92c6.6 0 12 5.4 12 12v56z"></path>
            	</svg>
           	</a>

        </div>

        <div class="table-responsive">
            <table class="table table-hover" id="datatable-grid">
                <thead>
                    <tr>
                    	<th>Name</th>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Created At</th>
                        <th>Updated At</th>
                        <th>&nbsp; &nbsp; &nbsp;&nbsp; Aksi &nbsp;&nbsp; &nbsp;</th>
                    </tr>
                </thead>
                
            </table>
        </div>
</div>
@endsection


@section('script')
<script type="text/javascript">
	$(document).ready(function() {
		var dataTable = $('#datatable-grid').DataTable( {
			drawCallback: function () {
			    $('[data-toggle="tooltip"]').tooltip();
			},
			processing    : false,
			serverSide    : true,
			bLengthChange : true,
			"oLanguage": {
				"sProcessing": "loading...",
                "oPaginate": { 
                	"sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>', "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>' 
                },

            	"sInfo": "Menampilkan halaman _PAGE_ of _PAGES_, total rekod _TOTAL_",
            	"sInfoEmpty": "Menampilkan halaman _PAGE_ of _PAGES_, total rekod _TOTAL_",
            
            	"sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
            
            	"sSearchPlaceholder": "Cari...",

           		"sLengthMenu": "Filter :  _MENU_",

           		"sEmptyTable": "Tidak ada data untuk ditampilkan"
            },
            "stripeClasses": [],
            
			ajax :{
			    url :"{{ route('acl.users.userJson') }}", // json datasource
			    type: "get",  // method  , by default get
			    error: function(request, status, error){  // error handling
			        
			        console.log(request.responseText);
			        
			    }
			},
			columns: [
				{data: 'name', name: 'name'},
	            {data: 'username', name: 'username'},
	            {data: 'email', name: 'email'},
	            {data: 'created_at', name: 'created_at'},
	            {data: 'updated_at', name: 'updated_at'},
	            {
	                data: 'action', 
	                name: 'action', 
	                orderable: true, 
	                searchable: true
	            },
	        ]

		});
        
    });

    function loadAddForm(){
    	$.ajax({
	        url: "{{ route('acl.users.addform') }}",
	        type: "post",
	        data: {"_token": "{{ csrf_token() }}"},
	        cache: false,
	        beforeSend: function(){
	            $("#loader").show();
	        },
	        success: function(data) {       
	            $('#modal_md_content').html(data);       
	        },error: function(request, status, error){
	           console.log(request.responseText);
	        },complete: function(){
	            $("#loader").hide();
	        }
	    });
    }

</script>
@endsection